### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by schumannd** [leecrossley/cordova-plugin-native-transitions#11] opened 2017-10-10 19:22 UTC
Android also has native transitions. Is it planned, that they will be included? For this to be a usable cordova plugin (which is usually used for cross platfomr development) this would make this plugin much more useful.

**Comment by razaviv** [comment] 2018-01-25 14:40
Make it for Android too, iOS is anyway has good transitions.

**Comment by leecrossley** [comment] 2018-01-25 15:59
Duplicate of #3 [comment](https://github.com/leecrossley/cordova-plugin-native-transitions/issues/3#issuecomment-62816246)

**Closed as completed by leecrossley** 2018-01-25 15:59 UTC
